### PR TITLE
Update write.id3v2.php available frames

### PR DESCRIPTION
**Pull request by Preau**
While trying to rewrite ID3v2 tags I've read using getID3 I noticed reading and writing wasn't compatible with each other.

I've updated the tag list in write.id3v2.php to be compatible with the one in module.tag.id3v2.php.
This included adding missing frames and changing some names for existing ones.

### CODE REVIEW

**Comment by JamesHeinrich** [comment]
It would've been nicer if you hadn't changed the leading whitespace so the actual changes were more readily apparent rather than a mass of deletions and additions with no clear differentiation as to what was changed vs what had spaces removed.

I'll assume your change is accurate and merge it anyways.

**Comment by duncan3dc** [comment]
@JamesHeinrich While I agree that the whitespace changes should have been in a separate commit, GitHub does have a feature to make viewing changes like this easier: https://github.com/JamesHeinrich/getID3/pull/84/files?w=1

**Comment by JamesHeinrich** [comment]
Well that certainly does look much better, thanks!
Why can't I find a link to toggle to that view on the Files Changed page, or am I blind?

**Comment by duncan3dc** [comment]
There isn't one unfortunately, it's a [secret feature](https://github.com/blog/967-github-secrets)

**Pull request merged**
