### PR TITLE
Read imagesize from $imgData

### PR DESCRIPTION
**Pull request by kesselb**
Alter GetDataImageSize to read the imagesize from image data instead of writing it to disk first.

Initially reported to nextcloud: https://github.com/nextcloud/server/issues/17291

I'm not sure if you need the temp dir logic somewhere else. Have not tested the pr extensively.

### CODE REVIEW

**Comment by StudioMaX** [comment]
`getimagesizefromstring` introduced since PHP 5.4, but, unfortunately, getID currently requires PHP 5.3.0 in composer.json

**Comment by kesselb** [comment]
> unfortunately, getID currently requires PHP 5.3.0 in composer.json

Fine by me.

**Comment by JamesHeinrich** [comment]
@kesselb Your idea is worthwhile. If you wrap it into a conditional block that falls back to the old code that would provide the benefits of simpler/faster code to most users with PHP v5.4+ and fall back to the older/slower code for v5.3 users.
```
public static function GetDataImageSize($imgData, &$imageinfo=array()) {
	if (function_exists('getimagesizefromstring')) {
		$GetDataImageSize = @getimagesizefromstring($imgData, $imageinfo);
		if ($GetDataImageSize === false || !isset($GetDataImageSize[0], $GetDataImageSize[1])) {
			return false;
		}
		return [
			'height' => $GetDataImageSize[0],
			'width'  => $GetDataImageSize[1]
		];
	}
	<rest of old code>
```
If you want to submit the change similar to above I'll be happy to merge it.

**Comment by kesselb** [comment]
OK. I just noticed a regression in my above code. The methods returns an array with 6 elements (0, 1, 2, 3, height and width) before and 2 elements (height and width) after.

**Pull request closed without merging**
