### PR TITLE
fix so paths will not be disclosed

### PR DESCRIPTION
**Pull request by carl-alberto**
Closes issue: https://github.com/JamesHeinrich/getID3/issues/235

When merged to WP core, it will also fix this issue: https://core.trac.wordpress.org/ticket/49499

### CODE REVIEW

**Comment by JamesHeinrich** [comment]
Your change involves adding this to the top of a number of modules:
```
if (!defined('ABSPATH')) {
	exit;
}
```
But where is ABSPATH defined/set?

**Comment by StudioMaX** [comment]
`ABSPATH` is something coming from WordPress (https://github.com/WordPress/WordPress/blob/master/wp-load.php#L20-L22).
Probably we can check `GETID3_INCLUDEPATH` instead.

**Comment by JamesHeinrich** [comment]
Checking `GETID3_INCLUDEPATH` would make sense, `ABSPATH` does not.

**Comment by carl-alberto** [comment]
Thanks for the feedback @JamesHeinrich and @StudioMaX. I updated my PR to reflect your suggestions. :)

**Comment by carl-alberto** [comment]
Thanks for merging!

**Pull request merged**
